name: sast
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '23 4 * * 1'
permissions:
  contents: read
jobs:
  vala-warnings:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Vala and GLib
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends valac libglib2.0-dev
      - run: make analyze
